# Generated by Django 3.2.5 on 2021-07-05 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('date_released',)},
        ),
        migrations.AlterModelOptions(
            name='moviereview',
            options={'ordering': ('date_created',)},
        ),
        migrations.RenameField(
            model_name='moviereview',
            old_name='review',
            new_name='content',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
